// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechWizard.Data;

namespace TechWizard.Data.Migrations
{
    [DbContext(typeof(WizardDbContext))]
    partial class WizardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "7a7be58a-9eca-403c-8c5d-2d8c2e3bb7ef",
                            ConcurrencyStamp = "9c4cb918-9be8-41fd-bb7a-40b75aebc037",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "dd231ff5-5cf5-41f5-ba39-ffbce9aa933f",
                            ConcurrencyStamp = "89891c77-9ac3-4e52-bf51-a15e012463f1",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "24ab6a6c-14f1-4b49-8964-ecfcbce372a3",
                            RoleId = "7a7be58a-9eca-403c-8c5d-2d8c2e3bb7ef"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("TechWizard.Data.Models.Entities.AttributeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AttributeTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "CPU Manufacturer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Socket"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Chipset"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Memory type"
                        },
                        new
                        {
                            Id = 5,
                            Name = "CPU model"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Amount of cores"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Amount of threads"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Frequency"
                        },
                        new
                        {
                            Id = 9,
                            Name = "GPU model"
                        },
                        new
                        {
                            Id = 10,
                            Name = "GPU Manufacturer"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Capacity"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Latency"
                        },
                        new
                        {
                            Id = 13,
                            Name = "RPM"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Buffer"
                        },
                        new
                        {
                            Id = 15,
                            Name = "SSD format"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Writing speed"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Reading speed"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Power output"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Color"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Size"
                        });
                });

            modelBuilder.Entity("TechWizard.Data.Models.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "ASUS"
                        },
                        new
                        {
                            Id = 2,
                            Name = "GIGABYTE"
                        },
                        new
                        {
                            Id = 3,
                            Name = "MSI"
                        },
                        new
                        {
                            Id = 4,
                            Name = "SAPPHIRE"
                        },
                        new
                        {
                            Id = 5,
                            Name = "AMD"
                        },
                        new
                        {
                            Id = 6,
                            Name = "INTEL"
                        },
                        new
                        {
                            Id = 7,
                            Name = "MS"
                        },
                        new
                        {
                            Id = 8,
                            Name = "ARMAGGEDDON"
                        },
                        new
                        {
                            Id = 9,
                            Name = "KINGSTON"
                        },
                        new
                        {
                            Id = 10,
                            Name = "GEIL"
                        },
                        new
                        {
                            Id = 11,
                            Name = "CRUCIAL"
                        },
                        new
                        {
                            Id = 12,
                            Name = "WESTERN DIGITAL"
                        },
                        new
                        {
                            Id = 13,
                            Name = "SEAGATE"
                        },
                        new
                        {
                            Id = 14,
                            Name = "TOSHIBA"
                        },
                        new
                        {
                            Id = 15,
                            Name = "SAMSUNG"
                        },
                        new
                        {
                            Id = 16,
                            Name = "CHIEFTEC"
                        },
                        new
                        {
                            Id = 17,
                            Name = "COOLER MASTER"
                        },
                        new
                        {
                            Id = 18,
                            Name = "LC-POWER"
                        },
                        new
                        {
                            Id = 19,
                            Name = "FSP"
                        },
                        new
                        {
                            Id = 20,
                            Name = "CORSAIR"
                        },
                        new
                        {
                            Id = 21,
                            Name = "G.SKILL"
                        },
                        new
                        {
                            Id = 22,
                            Name = "GAINWARD"
                        },
                        new
                        {
                            Id = 23,
                            Name = "ZOTAC"
                        },
                        new
                        {
                            Id = 24,
                            Name = "THERMALTAKE"
                        },
                        new
                        {
                            Id = 25,
                            Name = "REDRAGON"
                        },
                        new
                        {
                            Id = 26,
                            Name = "AS ROCK"
                        });
                });

            modelBuilder.Entity("TechWizard.Data.Models.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<bool>("OnPromotion")
                        .HasColumnType("bit");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Quantity")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("TypeId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            IsVisible = true,
                            Name = "Asus Prime B550-PLUS",
                            OnPromotion = false,
                            Picture = "/images/ASUSPRIMEB550PLUS.png",
                            Price = 209m,
                            ProductCode = "C769DC4E-E32E-49DF",
                            Quantity = 88,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 3,
                            IsVisible = true,
                            Name = "MSI B450 Gaming PLUS MAX",
                            OnPromotion = true,
                            Picture = "/images/image5da5cafd9a2b9.png",
                            Price = 159m,
                            ProductCode = "1359BD87-20CD-4B57",
                            Quantity = 23,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 1,
                            IsVisible = true,
                            Name = "Asus TUF Gaming B660M-PLUS Wifi D4",
                            OnPromotion = false,
                            Picture = "/images/image61fd2b7e9bba4.png",
                            Price = 249m,
                            ProductCode = "7E17F2CA-7551-4FB6",
                            Quantity = 65,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 2,
                            IsVisible = true,
                            Name = "Gigabyte Z590I AORUS ULTRA",
                            OnPromotion = false,
                            Picture = "/images/GIGABYTE-Z590I-AORUS-ULTRA.png",
                            Price = 399m,
                            ProductCode = "E1CC7C1F-F24B-4A0D",
                            Quantity = 36,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 3,
                            IsVisible = true,
                            Name = "MSI Z590 PRO Wifi",
                            OnPromotion = false,
                            Picture = "/images/image62458b01608fa.png",
                            Price = 219m,
                            ProductCode = "F3623C46-CB95-46F4",
                            Quantity = 73,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 6,
                            IsVisible = true,
                            Name = "Intel Core i5-10600 3.3GHz (4.8GHz)",
                            OnPromotion = false,
                            Picture = "/images/image5ec863b23325c.png",
                            Price = 319m,
                            ProductCode = "E016E9AB-B8CE-4CC4",
                            Quantity = 57,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 6,
                            IsVisible = true,
                            Name = "Intel Core i9-12900 3.2GHz (5.2GHz)",
                            OnPromotion = true,
                            Picture = "/images/image61e1691968cfd.png",
                            Price = 899m,
                            ProductCode = "76F9939B-6AA5-4D1F",
                            Quantity = 20,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 6,
                            IsVisible = true,
                            Name = "Intel Core i7-11700 2.5GHz (4.9GHz)",
                            OnPromotion = false,
                            Picture = "/images/image62a9bde3e51e1.png",
                            Price = 479m,
                            ProductCode = "B8B11D91-44D5-40A2",
                            Quantity = 74,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 5,
                            IsVisible = true,
                            Name = "AMD Ryzen 7 3800X 3.9GHz (4.5GHz)",
                            OnPromotion = false,
                            Picture = "/images/image5d66752a42531.png",
                            Price = 449m,
                            ProductCode = "38AC8CE3-34D3-4DED",
                            Quantity = 46,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 5,
                            IsVisible = true,
                            Name = "AMD Ryzen 7 5800X3D 3.4GHz (4.5GHz)",
                            OnPromotion = false,
                            Picture = "/images/image62728b1684f03.png",
                            Price = 699m,
                            ProductCode = "99AB880F-32F3-4B3D",
                            Quantity = 86,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 1,
                            IsVisible = true,
                            Name = "Asus TUF Gaming GeForce RTX 3060 12GB GDDR6 192-bit",
                            OnPromotion = false,
                            Picture = "/images/ASUS-TUF-Gaming-GeForce-RTX-3060.png",
                            Price = 749m,
                            ProductCode = "FDDE1F79-33D2-45FC",
                            Quantity = 26,
                            TypeId = 3
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 3,
                            IsVisible = true,
                            Name = "MSI GeForce RTX 2060 VENTUS 6GB GDDR6 192-bit",
                            OnPromotion = false,
                            Picture = "/images/image614d8cbf61188.png",
                            Price = 599m,
                            ProductCode = "9AD6F240-3EAF-4F43",
                            Quantity = 34,
                            TypeId = 3
                        },
                        new
                        {
                            Id = 13,
                            BrandId = 1,
                            IsVisible = true,
                            Name = "Asus TUF Gaming GeForce RTX 3080Ti 12GB GDDR6X 384-bit",
                            OnPromotion = true,
                            Picture = "/images/ASSUS TUF RTX 3080.png",
                            Price = 2499m,
                            ProductCode = "301F218F-1838-42F3",
                            Quantity = 15,
                            TypeId = 3
                        },
                        new
                        {
                            Id = 14,
                            BrandId = 2,
                            IsVisible = true,
                            Name = "Gigabyte AMD Radeon RX6700 XT EAGLE 12GB GDDR6 192-bit",
                            OnPromotion = false,
                            Picture = "/images/gigabyterx6700xtEagle.png",
                            Price = 899m,
                            ProductCode = "6676BC3B-217E-43D8",
                            Quantity = 22,
                            TypeId = 3
                        },
                        new
                        {
                            Id = 15,
                            BrandId = 4,
                            IsVisible = true,
                            Name = "Sapphire PULSE AMD Radeon RX6500 XT 4GB GDDR6 64-bit",
                            OnPromotion = true,
                            Picture = "/images/rx6500xt.png",
                            Price = 349m,
                            ProductCode = "6030F440-B958-4B7D",
                            Quantity = 12,
                            TypeId = 3
                        },
                        new
                        {
                            Id = 16,
                            BrandId = 9,
                            IsVisible = true,
                            Name = "Kingston Beast RGB 8GB DDR4 3733MHz CL19",
                            OnPromotion = false,
                            Picture = "/images/ddr48gb3733.png",
                            Price = 69m,
                            ProductCode = "C8A9A9B8-ED5B-4DEE",
                            Quantity = 76,
                            TypeId = 4
                        },
                        new
                        {
                            Id = 17,
                            BrandId = 9,
                            IsVisible = true,
                            Name = "Kingston Renegade RGB 32GB DDR4 3600MHz CL18",
                            OnPromotion = true,
                            Picture = "/images/32gb3600.png",
                            Price = 239m,
                            ProductCode = "3EEBAC20-4EC3-45E6",
                            Quantity = 28,
                            TypeId = 4
                        },
                        new
                        {
                            Id = 18,
                            BrandId = 9,
                            IsVisible = true,
                            Name = "Kingston Fury Beast 16GB DDR5 6000MHz CL40",
                            OnPromotion = false,
                            Picture = "/images/ddr516gb.png",
                            Price = 209m,
                            ProductCode = "AB3F5085-67B7-433D",
                            Quantity = 52,
                            TypeId = 4
                        },
                        new
                        {
                            Id = 19,
                            BrandId = 10,
                            IsVisible = true,
                            Name = "Geil Orion RGB 32GB (2x16GB) DDR4 3200MHz CL16",
                            OnPromotion = false,
                            Picture = "/images/geilDDR.png",
                            Price = 199m,
                            ProductCode = "D2B2102E-472F-489D",
                            Quantity = 43,
                            TypeId = 4
                        },
                        new
                        {
                            Id = 20,
                            BrandId = 9,
                            IsVisible = true,
                            Name = "Kingston Fury RGB 128GB (4x32GB) DDR4 3600MHz CL18",
                            OnPromotion = false,
                            Picture = "/images/4x32kingston.png",
                            Price = 889m,
                            ProductCode = "95E28014-A052-49F9",
                            Quantity = 60,
                            TypeId = 4
                        },
                        new
                        {
                            Id = 21,
                            BrandId = 12,
                            IsVisible = true,
                            Name = "WD 10TB 3.5 256MB 7200rpm NAS RedPlus",
                            OnPromotion = true,
                            Picture = "/images/WD-10TB-3.5.png",
                            Price = 449m,
                            ProductCode = "378E628D-EDAF-4B25",
                            Quantity = 19,
                            TypeId = 5
                        },
                        new
                        {
                            Id = 22,
                            BrandId = 12,
                            IsVisible = true,
                            Name = "WD 2TB 3.5 128MB 5400rpm NAS RedPlus",
                            OnPromotion = false,
                            Picture = "/images/image61ee87ed2e535.png",
                            Price = 119m,
                            ProductCode = "64A8ACB9-B32F-404C",
                            Quantity = 93,
                            TypeId = 5
                        },
                        new
                        {
                            Id = 23,
                            BrandId = 14,
                            IsVisible = true,
                            Name = "Toshiba 8TB 3.5 256MB 7200rpm X300",
                            OnPromotion = false,
                            Picture = "/images/723844000288-min-86.png",
                            Price = 279m,
                            ProductCode = "69CAEB14-8A39-42D6",
                            Quantity = 14,
                            TypeId = 5
                        },
                        new
                        {
                            Id = 24,
                            BrandId = 13,
                            IsVisible = true,
                            Name = "Seagate 2TB 2.5 128MB 5400rpm Baracuda",
                            OnPromotion = false,
                            Picture = "/images/image5bb5c5a17f576.png",
                            Price = 109m,
                            ProductCode = "704403C2-0408-4E21",
                            Quantity = 66,
                            TypeId = 5
                        },
                        new
                        {
                            Id = 25,
                            BrandId = 13,
                            IsVisible = true,
                            Name = "Seagate 2TB 3.5 SATA III 256MB 7200rpm",
                            OnPromotion = false,
                            Picture = "/images/image58b5545e696ff.png",
                            Price = 79m,
                            ProductCode = "A8477DD6-6975-469E",
                            Quantity = 35,
                            TypeId = 5
                        },
                        new
                        {
                            Id = 26,
                            BrandId = 15,
                            IsVisible = true,
                            Name = "Samsung SSD 970 EVO PLUS 500GB M.2 2280",
                            OnPromotion = false,
                            Picture = "/images/image5c6fdb548f82f1.png",
                            Price = 109m,
                            ProductCode = "09069E93-9244-40A4",
                            Quantity = 33,
                            TypeId = 6
                        },
                        new
                        {
                            Id = 27,
                            BrandId = 15,
                            IsVisible = true,
                            Name = "Samsung 2TB SSD 970 EVO PLUS M.2 2280",
                            OnPromotion = false,
                            Picture = "/images/samsung2TB.png",
                            Price = 359m,
                            ProductCode = "CE7E8FC9-53FF-4D89",
                            Quantity = 47,
                            TypeId = 6
                        },
                        new
                        {
                            Id = 28,
                            BrandId = 15,
                            IsVisible = true,
                            Name = "Samsung SSD 970 EVO PLUS 250G M.2 2280",
                            OnPromotion = false,
                            Picture = "/images/samsung250gb.png",
                            Price = 79m,
                            ProductCode = "EE32FDA4-1AC6-4A8F",
                            Quantity = 0,
                            TypeId = 6
                        },
                        new
                        {
                            Id = 29,
                            BrandId = 2,
                            IsVisible = true,
                            Name = "Gigabyte AORUS NVMe Gen4 SSD 1TB",
                            OnPromotion = true,
                            Picture = "/images/image5e01e2654eda2.png",
                            Price = 239m,
                            ProductCode = "40069663-75A5-4A89",
                            Quantity = 77,
                            TypeId = 6
                        },
                        new
                        {
                            Id = 30,
                            BrandId = 11,
                            IsVisible = true,
                            Name = "Crucial SSD 250GB PCIe M.2 280 P2",
                            OnPromotion = false,
                            Picture = "/images/image5ef48b1fa2009.png",
                            Price = 54m,
                            ProductCode = "1D47EAE9-74D5-4FEB",
                            Quantity = 1,
                            TypeId = 6
                        },
                        new
                        {
                            Id = 31,
                            BrandId = 7,
                            IsVisible = true,
                            Name = "MS CORE M500 80 Plus Platinum Pro 500W",
                            OnPromotion = false,
                            Picture = "/images/MS-Napajanje-CORE-M500-80-Plus-PLATINUM-PRO-39.png",
                            Price = 59m,
                            ProductCode = "66352EAF-BF17-4DBC",
                            Quantity = 36,
                            TypeId = 7
                        },
                        new
                        {
                            Id = 32,
                            BrandId = 17,
                            IsVisible = true,
                            Name = "CoolerMaster XG750 Platinum Plus 750W",
                            OnPromotion = true,
                            Picture = "/images/image6246d3ec405ae.png",
                            Price = 379m,
                            ProductCode = "FF845915-1C77-4F81",
                            Quantity = 36,
                            TypeId = 7
                        },
                        new
                        {
                            Id = 33,
                            BrandId = 8,
                            IsVisible = true,
                            Name = "Armaggeddon VOLTRON BRONZE 235FX 242W",
                            OnPromotion = false,
                            Picture = "/images/image5d9b4a2c06d5b.png",
                            Price = 29m,
                            ProductCode = "0E9656FC-8D9A-4E73",
                            Quantity = 36,
                            TypeId = 7
                        },
                        new
                        {
                            Id = 34,
                            BrandId = 17,
                            IsVisible = true,
                            Name = "CoolerMaster 500W ELITE",
                            OnPromotion = false,
                            Picture = "/images/image5aa929bb5ba6c.png",
                            Price = 74m,
                            ProductCode = "11CF1670-A053-4068",
                            Quantity = 36,
                            TypeId = 7
                        },
                        new
                        {
                            Id = 35,
                            BrandId = 16,
                            IsVisible = true,
                            Name = "Chieftec BBS-700S",
                            OnPromotion = false,
                            Picture = "/images/image5d09f7085dbf2.png",
                            Price = 129m,
                            ProductCode = "F09C7496-7F2D-4811",
                            Quantity = 36,
                            TypeId = 7
                        },
                        new
                        {
                            Id = 36,
                            BrandId = 18,
                            IsVisible = true,
                            Name = "LC-Power Gaming 992W Solar Flare",
                            OnPromotion = false,
                            Picture = "/images/image5f9ffbf28c1e6.png",
                            Price = 74m,
                            ProductCode = "B8FA88A9-EF9C-470A",
                            Quantity = 36,
                            TypeId = 8
                        },
                        new
                        {
                            Id = 37,
                            BrandId = 19,
                            IsVisible = true,
                            Name = "FSP CMT340 PLUS",
                            OnPromotion = false,
                            Picture = "/images/image6239999ddf98c.png",
                            Price = 119m,
                            ProductCode = "AC1D0EF6-3959-49FC",
                            Quantity = 1,
                            TypeId = 8
                        },
                        new
                        {
                            Id = 38,
                            BrandId = 7,
                            IsVisible = true,
                            Name = "MS Gaming ARMOR V500",
                            OnPromotion = true,
                            Picture = "/images/MS-Kućište-ARMOR-V500-.png",
                            Price = 59m,
                            ProductCode = "7E0E1595-CD05-467A",
                            Quantity = 2,
                            TypeId = 8
                        },
                        new
                        {
                            Id = 39,
                            BrandId = 17,
                            IsVisible = true,
                            Name = "CoolerMaster MasterBox MB311L ARGB",
                            OnPromotion = false,
                            Picture = "/images/COOLER-MASTER-Kućište-MASTERBOX-MB311L-ARGB-MCB-B311L-KGNN-S02-54.png",
                            Price = 112m,
                            ProductCode = "BC9AA633-8D14-4241",
                            Quantity = 8,
                            TypeId = 8
                        },
                        new
                        {
                            Id = 40,
                            BrandId = 8,
                            IsVisible = true,
                            Name = "Armaggeddon NIMITZ TR 1100",
                            OnPromotion = false,
                            Picture = "/images/image62b1765247c79.png",
                            Price = 59m,
                            ProductCode = "466C4DE4-1FA9-4D20",
                            Quantity = 14,
                            TypeId = 8
                        });
                });

            modelBuilder.Entity("TechWizard.Data.Models.Entities.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ProductTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Motherboard"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Processor"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Graphics card"
                        },
                        new
                        {
                            Id = 4,
                            Name = "RAM memory"
                        },
                        new
                        {
                            Id = 5,
                            Name = "HDD"
                        },
                        new
                        {
                            Id = 6,
                            Name = "SSD"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Power supply"
                        },
                        new
                        {
                            Id = 8,
                            Name = "PC Case"
                        });
                });

            modelBuilder.Entity("TechWizard.Data.Models.Entities.WizardUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "24ab6a6c-14f1-4b49-8964-ecfcbce372a3",
                            AccessFailedCount = 0,
                            City = "Belgrade",
                            ConcurrencyStamp = "abccc67e-66f3-42ce-a209-58dfeeb0d1bc",
                            Email = "nicjpa89@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Nikola",
                            LastName = "Panic",
                            LockoutEnabled = false,
                            NormalizedEmail = "NICJPA89@GMAIL.COM",
                            NormalizedUserName = "NICJPA89@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEPf+1qU7UIyj1ZNkVHZ04rndr0OJ6bqaCgOLB7BgSRbHkr/cq6Nt8Fyy90eMSvuDgg==",
                            PhoneNumber = "+381605605093",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bafc6bbc-7be4-48ed-86e4-a0401179b14a",
                            StreetAddress = "HadziMelentijeva 53",
                            TwoFactorEnabled = false,
                            UserName = "nicjpa89@gmail.com"
                        });
                });

            modelBuilder.Entity("TechWizard.Data.Models.Many2ManyEntities.ProductType_AttributeType", b =>
                {
                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int");

                    b.Property<int>("AttributeTypeId")
                        .HasColumnType("int");

                    b.HasKey("ProductTypeId", "AttributeTypeId");

                    b.HasIndex("AttributeTypeId");

                    b.ToTable("ProductTypes_AttributeTypes");

                    b.HasData(
                        new
                        {
                            ProductTypeId = 1,
                            AttributeTypeId = 1
                        },
                        new
                        {
                            ProductTypeId = 1,
                            AttributeTypeId = 2
                        },
                        new
                        {
                            ProductTypeId = 1,
                            AttributeTypeId = 3
                        },
                        new
                        {
                            ProductTypeId = 1,
                            AttributeTypeId = 4
                        },
                        new
                        {
                            ProductTypeId = 2,
                            AttributeTypeId = 2
                        },
                        new
                        {
                            ProductTypeId = 2,
                            AttributeTypeId = 5
                        },
                        new
                        {
                            ProductTypeId = 2,
                            AttributeTypeId = 6
                        },
                        new
                        {
                            ProductTypeId = 2,
                            AttributeTypeId = 7
                        },
                        new
                        {
                            ProductTypeId = 2,
                            AttributeTypeId = 8
                        },
                        new
                        {
                            ProductTypeId = 3,
                            AttributeTypeId = 10
                        },
                        new
                        {
                            ProductTypeId = 3,
                            AttributeTypeId = 9
                        },
                        new
                        {
                            ProductTypeId = 3,
                            AttributeTypeId = 4
                        },
                        new
                        {
                            ProductTypeId = 3,
                            AttributeTypeId = 11
                        },
                        new
                        {
                            ProductTypeId = 4,
                            AttributeTypeId = 4
                        },
                        new
                        {
                            ProductTypeId = 4,
                            AttributeTypeId = 11
                        },
                        new
                        {
                            ProductTypeId = 4,
                            AttributeTypeId = 8
                        },
                        new
                        {
                            ProductTypeId = 4,
                            AttributeTypeId = 12
                        },
                        new
                        {
                            ProductTypeId = 5,
                            AttributeTypeId = 11
                        },
                        new
                        {
                            ProductTypeId = 5,
                            AttributeTypeId = 13
                        },
                        new
                        {
                            ProductTypeId = 5,
                            AttributeTypeId = 14
                        },
                        new
                        {
                            ProductTypeId = 6,
                            AttributeTypeId = 15
                        },
                        new
                        {
                            ProductTypeId = 6,
                            AttributeTypeId = 11
                        },
                        new
                        {
                            ProductTypeId = 6,
                            AttributeTypeId = 17
                        },
                        new
                        {
                            ProductTypeId = 6,
                            AttributeTypeId = 16
                        },
                        new
                        {
                            ProductTypeId = 7,
                            AttributeTypeId = 18
                        },
                        new
                        {
                            ProductTypeId = 8,
                            AttributeTypeId = 19
                        },
                        new
                        {
                            ProductTypeId = 8,
                            AttributeTypeId = 20
                        });
                });

            modelBuilder.Entity("TechWizard.Data.Models.Many2ManyEntities.Product_AttributeType", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("AttributeTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId", "AttributeTypeId");

                    b.HasIndex("AttributeTypeId");

                    b.ToTable("Products_AttributeTypes");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            AttributeTypeId = 1,
                            Value = "AMD"
                        },
                        new
                        {
                            ProductId = 1,
                            AttributeTypeId = 2,
                            Value = "AMD AM4"
                        },
                        new
                        {
                            ProductId = 1,
                            AttributeTypeId = 3,
                            Value = "AMD B550"
                        },
                        new
                        {
                            ProductId = 1,
                            AttributeTypeId = 4,
                            Value = "DDR4"
                        },
                        new
                        {
                            ProductId = 2,
                            AttributeTypeId = 1,
                            Value = "AMD"
                        },
                        new
                        {
                            ProductId = 2,
                            AttributeTypeId = 2,
                            Value = "AMD AM4"
                        },
                        new
                        {
                            ProductId = 2,
                            AttributeTypeId = 3,
                            Value = "AMD B450"
                        },
                        new
                        {
                            ProductId = 2,
                            AttributeTypeId = 4,
                            Value = "DDR4"
                        },
                        new
                        {
                            ProductId = 3,
                            AttributeTypeId = 1,
                            Value = "Intel"
                        },
                        new
                        {
                            ProductId = 3,
                            AttributeTypeId = 2,
                            Value = "Intel 1700"
                        },
                        new
                        {
                            ProductId = 3,
                            AttributeTypeId = 3,
                            Value = "Intel B660"
                        },
                        new
                        {
                            ProductId = 3,
                            AttributeTypeId = 4,
                            Value = "DDR4"
                        },
                        new
                        {
                            ProductId = 4,
                            AttributeTypeId = 1,
                            Value = "Intel"
                        },
                        new
                        {
                            ProductId = 4,
                            AttributeTypeId = 2,
                            Value = "Intel 1200"
                        },
                        new
                        {
                            ProductId = 4,
                            AttributeTypeId = 3,
                            Value = "Intel Z590"
                        },
                        new
                        {
                            ProductId = 4,
                            AttributeTypeId = 4,
                            Value = "DDR4"
                        },
                        new
                        {
                            ProductId = 5,
                            AttributeTypeId = 1,
                            Value = "Intel"
                        },
                        new
                        {
                            ProductId = 5,
                            AttributeTypeId = 2,
                            Value = "Intel 1200"
                        },
                        new
                        {
                            ProductId = 5,
                            AttributeTypeId = 3,
                            Value = "Intel Z590"
                        },
                        new
                        {
                            ProductId = 5,
                            AttributeTypeId = 4,
                            Value = "DDR4"
                        },
                        new
                        {
                            ProductId = 6,
                            AttributeTypeId = 2,
                            Value = "Intel 1200"
                        },
                        new
                        {
                            ProductId = 6,
                            AttributeTypeId = 5,
                            Value = "Intel Core i5"
                        },
                        new
                        {
                            ProductId = 6,
                            AttributeTypeId = 8,
                            Value = "3.3 GHz"
                        },
                        new
                        {
                            ProductId = 6,
                            AttributeTypeId = 6,
                            Value = "6"
                        },
                        new
                        {
                            ProductId = 6,
                            AttributeTypeId = 7,
                            Value = "12"
                        },
                        new
                        {
                            ProductId = 7,
                            AttributeTypeId = 2,
                            Value = "Intel 1700"
                        },
                        new
                        {
                            ProductId = 7,
                            AttributeTypeId = 5,
                            Value = "Intel Core i9"
                        },
                        new
                        {
                            ProductId = 7,
                            AttributeTypeId = 8,
                            Value = "3.2 GHz"
                        },
                        new
                        {
                            ProductId = 7,
                            AttributeTypeId = 6,
                            Value = "16"
                        },
                        new
                        {
                            ProductId = 7,
                            AttributeTypeId = 7,
                            Value = "24"
                        },
                        new
                        {
                            ProductId = 8,
                            AttributeTypeId = 2,
                            Value = "Intel 1200"
                        },
                        new
                        {
                            ProductId = 8,
                            AttributeTypeId = 5,
                            Value = "Intel Core i7"
                        },
                        new
                        {
                            ProductId = 8,
                            AttributeTypeId = 8,
                            Value = "2.5 GHz"
                        },
                        new
                        {
                            ProductId = 8,
                            AttributeTypeId = 6,
                            Value = "8"
                        },
                        new
                        {
                            ProductId = 8,
                            AttributeTypeId = 7,
                            Value = "16"
                        },
                        new
                        {
                            ProductId = 9,
                            AttributeTypeId = 2,
                            Value = "AMD AM4"
                        },
                        new
                        {
                            ProductId = 9,
                            AttributeTypeId = 5,
                            Value = "AMD Ryzen 7"
                        },
                        new
                        {
                            ProductId = 9,
                            AttributeTypeId = 8,
                            Value = "3.9 GHz"
                        },
                        new
                        {
                            ProductId = 9,
                            AttributeTypeId = 6,
                            Value = "8"
                        },
                        new
                        {
                            ProductId = 9,
                            AttributeTypeId = 7,
                            Value = "16"
                        },
                        new
                        {
                            ProductId = 10,
                            AttributeTypeId = 2,
                            Value = "AMD AM4"
                        },
                        new
                        {
                            ProductId = 10,
                            AttributeTypeId = 5,
                            Value = "AMD Ryzen 7"
                        },
                        new
                        {
                            ProductId = 10,
                            AttributeTypeId = 8,
                            Value = "3.4 GHz"
                        },
                        new
                        {
                            ProductId = 10,
                            AttributeTypeId = 6,
                            Value = "8"
                        },
                        new
                        {
                            ProductId = 10,
                            AttributeTypeId = 7,
                            Value = "16"
                        },
                        new
                        {
                            ProductId = 11,
                            AttributeTypeId = 10,
                            Value = "Nvidia"
                        },
                        new
                        {
                            ProductId = 11,
                            AttributeTypeId = 9,
                            Value = "GeForce RTX 3060"
                        },
                        new
                        {
                            ProductId = 11,
                            AttributeTypeId = 11,
                            Value = "12 GB"
                        },
                        new
                        {
                            ProductId = 11,
                            AttributeTypeId = 4,
                            Value = "GDDR6"
                        },
                        new
                        {
                            ProductId = 12,
                            AttributeTypeId = 10,
                            Value = "Nvidia"
                        },
                        new
                        {
                            ProductId = 12,
                            AttributeTypeId = 9,
                            Value = "GeForce RTX 2060"
                        },
                        new
                        {
                            ProductId = 12,
                            AttributeTypeId = 11,
                            Value = "6 GB"
                        },
                        new
                        {
                            ProductId = 12,
                            AttributeTypeId = 4,
                            Value = "GDDR6"
                        },
                        new
                        {
                            ProductId = 13,
                            AttributeTypeId = 10,
                            Value = "Nvidia"
                        },
                        new
                        {
                            ProductId = 13,
                            AttributeTypeId = 9,
                            Value = "GeForce RTX 3080 Ti"
                        },
                        new
                        {
                            ProductId = 13,
                            AttributeTypeId = 11,
                            Value = "12 GB"
                        },
                        new
                        {
                            ProductId = 13,
                            AttributeTypeId = 4,
                            Value = "GDDR6X"
                        },
                        new
                        {
                            ProductId = 14,
                            AttributeTypeId = 10,
                            Value = "AMD"
                        },
                        new
                        {
                            ProductId = 14,
                            AttributeTypeId = 9,
                            Value = "Radeon RX 6700 XT"
                        },
                        new
                        {
                            ProductId = 14,
                            AttributeTypeId = 11,
                            Value = "12 GB"
                        },
                        new
                        {
                            ProductId = 14,
                            AttributeTypeId = 4,
                            Value = "GDDR6"
                        },
                        new
                        {
                            ProductId = 15,
                            AttributeTypeId = 10,
                            Value = "AMD"
                        },
                        new
                        {
                            ProductId = 15,
                            AttributeTypeId = 9,
                            Value = "Radeon RX 6500 XT"
                        },
                        new
                        {
                            ProductId = 15,
                            AttributeTypeId = 11,
                            Value = "4 GB"
                        },
                        new
                        {
                            ProductId = 15,
                            AttributeTypeId = 4,
                            Value = "GDDR6"
                        },
                        new
                        {
                            ProductId = 16,
                            AttributeTypeId = 11,
                            Value = "8 GB"
                        },
                        new
                        {
                            ProductId = 16,
                            AttributeTypeId = 4,
                            Value = "DDR4"
                        },
                        new
                        {
                            ProductId = 16,
                            AttributeTypeId = 8,
                            Value = "3733 MHz"
                        },
                        new
                        {
                            ProductId = 16,
                            AttributeTypeId = 12,
                            Value = "CL19"
                        },
                        new
                        {
                            ProductId = 17,
                            AttributeTypeId = 11,
                            Value = "32 GB"
                        },
                        new
                        {
                            ProductId = 17,
                            AttributeTypeId = 4,
                            Value = "DDR4"
                        },
                        new
                        {
                            ProductId = 17,
                            AttributeTypeId = 8,
                            Value = "3600 MHz"
                        },
                        new
                        {
                            ProductId = 17,
                            AttributeTypeId = 12,
                            Value = "CL18"
                        },
                        new
                        {
                            ProductId = 18,
                            AttributeTypeId = 11,
                            Value = "16 GB"
                        },
                        new
                        {
                            ProductId = 18,
                            AttributeTypeId = 4,
                            Value = "DDR5"
                        },
                        new
                        {
                            ProductId = 18,
                            AttributeTypeId = 8,
                            Value = "6000 MHz"
                        },
                        new
                        {
                            ProductId = 18,
                            AttributeTypeId = 12,
                            Value = "CL40"
                        },
                        new
                        {
                            ProductId = 19,
                            AttributeTypeId = 11,
                            Value = "32 GB"
                        },
                        new
                        {
                            ProductId = 19,
                            AttributeTypeId = 4,
                            Value = "DDR4"
                        },
                        new
                        {
                            ProductId = 19,
                            AttributeTypeId = 8,
                            Value = "3200 MHz"
                        },
                        new
                        {
                            ProductId = 19,
                            AttributeTypeId = 12,
                            Value = "CL16"
                        },
                        new
                        {
                            ProductId = 20,
                            AttributeTypeId = 11,
                            Value = "128 GB"
                        },
                        new
                        {
                            ProductId = 20,
                            AttributeTypeId = 4,
                            Value = "DDR4"
                        },
                        new
                        {
                            ProductId = 20,
                            AttributeTypeId = 8,
                            Value = "3600 MHz"
                        },
                        new
                        {
                            ProductId = 20,
                            AttributeTypeId = 12,
                            Value = "CL18"
                        },
                        new
                        {
                            ProductId = 21,
                            AttributeTypeId = 11,
                            Value = "10 TB"
                        },
                        new
                        {
                            ProductId = 21,
                            AttributeTypeId = 13,
                            Value = "7200 RPM"
                        },
                        new
                        {
                            ProductId = 21,
                            AttributeTypeId = 14,
                            Value = "256 MB"
                        },
                        new
                        {
                            ProductId = 22,
                            AttributeTypeId = 11,
                            Value = "2 TB"
                        },
                        new
                        {
                            ProductId = 22,
                            AttributeTypeId = 13,
                            Value = "5400 RPM"
                        },
                        new
                        {
                            ProductId = 22,
                            AttributeTypeId = 14,
                            Value = "128 MB"
                        },
                        new
                        {
                            ProductId = 23,
                            AttributeTypeId = 11,
                            Value = "8 TB"
                        },
                        new
                        {
                            ProductId = 23,
                            AttributeTypeId = 13,
                            Value = "7200 RPM"
                        },
                        new
                        {
                            ProductId = 23,
                            AttributeTypeId = 14,
                            Value = "256 MB"
                        },
                        new
                        {
                            ProductId = 24,
                            AttributeTypeId = 11,
                            Value = "2 TB"
                        },
                        new
                        {
                            ProductId = 24,
                            AttributeTypeId = 13,
                            Value = "5400 RPM"
                        },
                        new
                        {
                            ProductId = 24,
                            AttributeTypeId = 14,
                            Value = "128 MB"
                        },
                        new
                        {
                            ProductId = 25,
                            AttributeTypeId = 11,
                            Value = "2 TB"
                        },
                        new
                        {
                            ProductId = 25,
                            AttributeTypeId = 13,
                            Value = "7200 RPM"
                        },
                        new
                        {
                            ProductId = 25,
                            AttributeTypeId = 14,
                            Value = "256 MB"
                        },
                        new
                        {
                            ProductId = 26,
                            AttributeTypeId = 15,
                            Value = "M.2 2280"
                        },
                        new
                        {
                            ProductId = 26,
                            AttributeTypeId = 11,
                            Value = "500 GB"
                        },
                        new
                        {
                            ProductId = 26,
                            AttributeTypeId = 17,
                            Value = "3500 MB/s"
                        },
                        new
                        {
                            ProductId = 26,
                            AttributeTypeId = 16,
                            Value = "3200 MB/s"
                        },
                        new
                        {
                            ProductId = 27,
                            AttributeTypeId = 15,
                            Value = "M.2 2280"
                        },
                        new
                        {
                            ProductId = 27,
                            AttributeTypeId = 11,
                            Value = "2 TB"
                        },
                        new
                        {
                            ProductId = 27,
                            AttributeTypeId = 17,
                            Value = "3500 MB/s"
                        },
                        new
                        {
                            ProductId = 27,
                            AttributeTypeId = 16,
                            Value = "3300 MB/s"
                        },
                        new
                        {
                            ProductId = 28,
                            AttributeTypeId = 15,
                            Value = "M.2 2280"
                        },
                        new
                        {
                            ProductId = 28,
                            AttributeTypeId = 11,
                            Value = "250 GB"
                        },
                        new
                        {
                            ProductId = 28,
                            AttributeTypeId = 17,
                            Value = "3500 MB/s"
                        },
                        new
                        {
                            ProductId = 28,
                            AttributeTypeId = 16,
                            Value = "2300 MB/s"
                        },
                        new
                        {
                            ProductId = 29,
                            AttributeTypeId = 15,
                            Value = "M.2 2280"
                        },
                        new
                        {
                            ProductId = 29,
                            AttributeTypeId = 11,
                            Value = "1 TB"
                        },
                        new
                        {
                            ProductId = 29,
                            AttributeTypeId = 17,
                            Value = "5000 MB/s"
                        },
                        new
                        {
                            ProductId = 29,
                            AttributeTypeId = 16,
                            Value = "4400 MB/s"
                        },
                        new
                        {
                            ProductId = 30,
                            AttributeTypeId = 15,
                            Value = "M.2 2280"
                        },
                        new
                        {
                            ProductId = 30,
                            AttributeTypeId = 11,
                            Value = "250 GB"
                        },
                        new
                        {
                            ProductId = 30,
                            AttributeTypeId = 17,
                            Value = "2100 MB/s"
                        },
                        new
                        {
                            ProductId = 30,
                            AttributeTypeId = 16,
                            Value = "1150 MB/s"
                        },
                        new
                        {
                            ProductId = 31,
                            AttributeTypeId = 18,
                            Value = "500W"
                        },
                        new
                        {
                            ProductId = 32,
                            AttributeTypeId = 18,
                            Value = "750W"
                        },
                        new
                        {
                            ProductId = 33,
                            AttributeTypeId = 18,
                            Value = "242W"
                        },
                        new
                        {
                            ProductId = 34,
                            AttributeTypeId = 18,
                            Value = "500W"
                        },
                        new
                        {
                            ProductId = 35,
                            AttributeTypeId = 18,
                            Value = "700W"
                        },
                        new
                        {
                            ProductId = 36,
                            AttributeTypeId = 20,
                            Value = "Midi Tower"
                        },
                        new
                        {
                            ProductId = 36,
                            AttributeTypeId = 19,
                            Value = "White"
                        },
                        new
                        {
                            ProductId = 37,
                            AttributeTypeId = 20,
                            Value = "Mini Tower"
                        },
                        new
                        {
                            ProductId = 37,
                            AttributeTypeId = 19,
                            Value = "Black"
                        },
                        new
                        {
                            ProductId = 38,
                            AttributeTypeId = 20,
                            Value = "Midi Tower"
                        },
                        new
                        {
                            ProductId = 38,
                            AttributeTypeId = 19,
                            Value = "Black"
                        },
                        new
                        {
                            ProductId = 39,
                            AttributeTypeId = 20,
                            Value = "Mini Tower"
                        },
                        new
                        {
                            ProductId = 39,
                            AttributeTypeId = 19,
                            Value = "Black"
                        },
                        new
                        {
                            ProductId = 40,
                            AttributeTypeId = 20,
                            Value = "Mini Tower"
                        },
                        new
                        {
                            ProductId = 40,
                            AttributeTypeId = 19,
                            Value = "Black"
                        });
                });

            modelBuilder.Entity("TechWizard.Data.Models.ShoppingCartEntities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AmountOfAllItems")
                        .HasColumnType("int");

                    b.Property<int>("AmountOfDiffernetItems")
                        .HasColumnType("int");

                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ShoppingCartId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("TotalCharge")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ShoppingCartId")
                        .IsUnique()
                        .HasFilter("[ShoppingCartId] IS NOT NULL");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TechWizard.Data.Models.ShoppingCartEntities.OrderDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumOfDifferntProducts")
                        .HasColumnType("int");

                    b.Property<string>("OrderNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalNumOfProducts")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("TechWizard.Data.Models.ShoppingCartEntities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Units")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("TechWizard.Data.Models.ShoppingCartEntities.ShoppingCart", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TechWizard.Data.Models.Entities.WizardUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TechWizard.Data.Models.Entities.WizardUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechWizard.Data.Models.Entities.WizardUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TechWizard.Data.Models.Entities.WizardUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TechWizard.Data.Models.Entities.Product", b =>
                {
                    b.HasOne("TechWizard.Data.Models.Entities.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechWizard.Data.Models.Entities.ProductType", "Type")
                        .WithMany("Products")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("TechWizard.Data.Models.Many2ManyEntities.ProductType_AttributeType", b =>
                {
                    b.HasOne("TechWizard.Data.Models.Entities.AttributeType", "AttributeType")
                        .WithMany("ProductTypes")
                        .HasForeignKey("AttributeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechWizard.Data.Models.Entities.ProductType", "ProductType")
                        .WithMany("Attributes")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeType");

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("TechWizard.Data.Models.Many2ManyEntities.Product_AttributeType", b =>
                {
                    b.HasOne("TechWizard.Data.Models.Entities.AttributeType", "AttributeType")
                        .WithMany("Products")
                        .HasForeignKey("AttributeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechWizard.Data.Models.Entities.Product", "Product")
                        .WithMany("Attributes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeType");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TechWizard.Data.Models.ShoppingCartEntities.Order", b =>
                {
                    b.HasOne("TechWizard.Data.Models.Entities.WizardUser", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("TechWizard.Data.Models.ShoppingCartEntities.ShoppingCart", "ShoppingCart")
                        .WithOne("ActiveOrder")
                        .HasForeignKey("TechWizard.Data.Models.ShoppingCartEntities.Order", "ShoppingCartId");

                    b.Navigation("Customer");

                    b.Navigation("ShoppingCart");
                });

            modelBuilder.Entity("TechWizard.Data.Models.ShoppingCartEntities.OrderItem", b =>
                {
                    b.HasOne("TechWizard.Data.Models.ShoppingCartEntities.Order", "Order")
                        .WithMany("AllItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechWizard.Data.Models.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TechWizard.Data.Models.ShoppingCartEntities.ShoppingCart", b =>
                {
                    b.HasOne("TechWizard.Data.Models.Entities.WizardUser", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("TechWizard.Data.Models.Entities.AttributeType", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("ProductTypes");
                });

            modelBuilder.Entity("TechWizard.Data.Models.Entities.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("TechWizard.Data.Models.Entities.Product", b =>
                {
                    b.Navigation("Attributes");
                });

            modelBuilder.Entity("TechWizard.Data.Models.Entities.ProductType", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("TechWizard.Data.Models.ShoppingCartEntities.Order", b =>
                {
                    b.Navigation("AllItems");
                });

            modelBuilder.Entity("TechWizard.Data.Models.ShoppingCartEntities.ShoppingCart", b =>
                {
                    b.Navigation("ActiveOrder");
                });
#pragma warning restore 612, 618
        }
    }
}
